//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace MemberShipManage.Domain
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class MembershipManageEntities : DbContext
    {
        public MembershipManageEntities()
            : base("name=MembershipManageEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<ConsumeRecord> ConsumeRecord { get; set; }
        public virtual DbSet<Customer> Customer { get; set; }
        public virtual DbSet<LoginRecord> LoginRecord { get; set; }
        public virtual DbSet<Users> Users { get; set; }
        public virtual DbSet<CustomerAmount> CustomerAmount { get; set; }
        public virtual DbSet<RechargeRecord> RechargeRecord { get; set; }
        public virtual DbSet<CustomerRebate> CustomerRebate { get; set; }
        public virtual DbSet<SystemConfig> SystemConfig { get; set; }
        public virtual DbSet<Dishes> Dishes { get; set; }
    }
}
